### ISSUE TITLE
Last two rows of .csv file do not have any responses recorded

### ISSUE THREAD

**Issue by dmbates** [cyhsieh-psy/SMLP_exercise#1]
In data row number 25280 all the columns, including `word` are missing.  I suggest this row be dropped.
In data row number 25281 only a few of the characterizations of the word are present but neither accuracy measures nor response times.  We can eliminate this row after reading but is there a purpose in reading the row at all?

Why do the row numbers start at 0?  Did you get the file from a Python or C programmer? 😁

**Comment by cyhsieh-psy** [comment]
I have uploaded a new file. 

That's a good observation! I used python to combine several datasets together.
