### ISSUE TITLE
Did you miss the definition of RT_inv?

### ISSUE THREAD

**Issue by dmbates** [cyhsieh-psy/SMLP_exercise#2]
In the code chunk labelled `model of RT` you have a response `RT_inv` that doesn't seem to be defined in the data frame.  Should that be defined as the inverse of `RT`?

**Comment by cyhsieh-psy** [comment]
I think I'm using `zRT` rather than `RT_inv` for this mode. I have changed the code accordingly. Sorry for the inconvenience.

**Comment by dmbates** [comment]
Thanks for making that change.

I think that zRT was not calculated correctly.  I created a Julia-based Quarto file to examine the data and fit some initial models.  I could send you the individual files or, if you prefer, create a pull request on this repository.  It would be easiest if you were to invite me to be a collaborator on the repository but however works for you.

**Comment by cyhsieh-psy** [comment]
I just invited you as a collaborator of the repo. 

`zRT` may not be wrong as each data point is the mean across participants. `zRT` is defined as "the mean of the standardized reaction time for each word computed across participants". I also changed the description in the script.

**Comment by dmbates** [comment]
Thank you for the explanation about `zRT`.  I saw that it said it was `z-transformed` in the code book section of your .Rmd document so I thought it was intended to be the  z-scores.
